//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("Models", "FK_UserInstance_Instance", "Instance", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReWeb.Instance), "UserInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReWeb.UserInstance), true)]

#endregion

namespace ReWeb
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ModelsContainer : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ModelsContainer”部分中的连接字符串初始化新 ModelsContainer 对象。
        /// </summary>
        public ModelsContainer() : base("name=ModelsContainer", "ModelsContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ModelsContainer 对象。
        /// </summary>
        public ModelsContainer(string connectionString) : base(connectionString, "ModelsContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ModelsContainer 对象。
        /// </summary>
        public ModelsContainer(EntityConnection connection) : base(connection, "ModelsContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Instance> Instance
        {
            get
            {
                if ((_Instance == null))
                {
                    _Instance = base.CreateObjectSet<Instance>("Instance");
                }
                return _Instance;
            }
        }
        private ObjectSet<Instance> _Instance;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UserInstance> UserInstance
        {
            get
            {
                if ((_UserInstance == null))
                {
                    _UserInstance = base.CreateObjectSet<UserInstance>("UserInstance");
                }
                return _UserInstance;
            }
        }
        private ObjectSet<UserInstance> _UserInstance;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UserInformation> UserInformation
        {
            get
            {
                if ((_UserInformation == null))
                {
                    _UserInformation = base.CreateObjectSet<UserInformation>("UserInformation");
                }
                return _UserInformation;
            }
        }
        private ObjectSet<UserInformation> _UserInformation;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Instance EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToInstance(Instance instance)
        {
            base.AddObject("Instance", instance);
        }
    
        /// <summary>
        /// 用于向 UserInstance EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUserInstance(UserInstance userInstance)
        {
            base.AddObject("UserInstance", userInstance);
        }
    
        /// <summary>
        /// 用于向 UserInformation EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUserInformation(UserInformation userInformation)
        {
            base.AddObject("UserInformation", userInformation);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Models", Name="Instance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Instance : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Instance 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static Instance CreateInstance(global::System.Int32 id)
        {
            Instance instance = new Instance();
            instance.ID = id;
            return instance;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DJH
        {
            get
            {
                return _DJH;
            }
            set
            {
                OnDJHChanging(value);
                ReportPropertyChanging("DJH");
                _DJH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DJH");
                OnDJHChanged();
            }
        }
        private global::System.String _DJH;
        partial void OnDJHChanging(global::System.String value);
        partial void OnDJHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TFH
        {
            get
            {
                return _TFH;
            }
            set
            {
                OnTFHChanging(value);
                ReportPropertyChanging("TFH");
                _TFH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TFH");
                OnTFHChanged();
            }
        }
        private global::System.String _TFH;
        partial void OnTFHChanging(global::System.String value);
        partial void OnTFHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FWZL
        {
            get
            {
                return _FWZL;
            }
            set
            {
                OnFWZLChanging(value);
                ReportPropertyChanging("FWZL");
                _FWZL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FWZL");
                OnFWZLChanged();
            }
        }
        private global::System.String _FWZL;
        partial void OnFWZLChanging(global::System.String value);
        partial void OnFWZLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QLRMC
        {
            get
            {
                return _QLRMC;
            }
            set
            {
                OnQLRMCChanging(value);
                ReportPropertyChanging("QLRMC");
                _QLRMC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QLRMC");
                OnQLRMCChanged();
            }
        }
        private global::System.String _QLRMC;
        partial void OnQLRMCChanging(global::System.String value);
        partial void OnQLRMCChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TDYT
        {
            get
            {
                return _TDYT;
            }
            set
            {
                OnTDYTChanging(value);
                ReportPropertyChanging("TDYT");
                _TDYT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TDYT");
                OnTDYTChanged();
            }
        }
        private global::System.String _TDYT;
        partial void OnTDYTChanging(global::System.String value);
        partial void OnTDYTChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZJLX
        {
            get
            {
                return _ZJLX;
            }
            set
            {
                OnZJLXChanging(value);
                ReportPropertyChanging("ZJLX");
                _ZJLX = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZJLX");
                OnZJLXChanged();
            }
        }
        private global::System.String _ZJLX;
        partial void OnZJLXChanging(global::System.String value);
        partial void OnZJLXChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZJBH
        {
            get
            {
                return _ZJBH;
            }
            set
            {
                OnZJBHChanging(value);
                ReportPropertyChanging("ZJBH");
                _ZJBH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZJBH");
                OnZJBHChanged();
            }
        }
        private global::System.String _ZJBH;
        partial void OnZJBHChanging(global::System.String value);
        partial void OnZJBHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DWXZ
        {
            get
            {
                return _DWXZ;
            }
            set
            {
                OnDWXZChanging(value);
                ReportPropertyChanging("DWXZ");
                _DWXZ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DWXZ");
                OnDWXZChanged();
            }
        }
        private global::System.String _DWXZ;
        partial void OnDWXZChanging(global::System.String value);
        partial void OnDWXZChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String YB
        {
            get
            {
                return _YB;
            }
            set
            {
                OnYBChanging(value);
                ReportPropertyChanging("YB");
                _YB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("YB");
                OnYBChanged();
            }
        }
        private global::System.String _YB;
        partial void OnYBChanging(global::System.String value);
        partial void OnYBChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QSXZ
        {
            get
            {
                return _QSXZ;
            }
            set
            {
                OnQSXZChanging(value);
                ReportPropertyChanging("QSXZ");
                _QSXZ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QSXZ");
                OnQSXZChanged();
            }
        }
        private global::System.String _QSXZ;
        partial void OnQSXZChanging(global::System.String value);
        partial void OnQSXZChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SYQLX
        {
            get
            {
                return _SYQLX;
            }
            set
            {
                OnSYQLXChanging(value);
                ReportPropertyChanging("SYQLX");
                _SYQLX = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SYQLX");
                OnSYQLXChanged();
            }
        }
        private global::System.String _SYQLX;
        partial void OnSYQLXChanging(global::System.String value);
        partial void OnSYQLXChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> FTMJ
        {
            get
            {
                return _FTMJ;
            }
            set
            {
                OnFTMJChanging(value);
                ReportPropertyChanging("FTMJ");
                _FTMJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FTMJ");
                OnFTMJChanged();
            }
        }
        private Nullable<global::System.Double> _FTMJ;
        partial void OnFTMJChanging(Nullable<global::System.Double> value);
        partial void OnFTMJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DYMJ
        {
            get
            {
                return _DYMJ;
            }
            set
            {
                OnDYMJChanging(value);
                ReportPropertyChanging("DYMJ");
                _DYMJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DYMJ");
                OnDYMJChanged();
            }
        }
        private Nullable<global::System.Double> _DYMJ;
        partial void OnDYMJChanging(Nullable<global::System.Double> value);
        partial void OnDYMJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BZ
        {
            get
            {
                return _BZ;
            }
            set
            {
                OnBZChanging(value);
                ReportPropertyChanging("BZ");
                _BZ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BZ");
                OnBZChanged();
            }
        }
        private global::System.String _BZ;
        partial void OnBZChanging(global::System.String value);
        partial void OnBZChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> SYQMJ
        {
            get
            {
                return _SYQMJ;
            }
            set
            {
                OnSYQMJChanging(value);
                ReportPropertyChanging("SYQMJ");
                _SYQMJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SYQMJ");
                OnSYQMJChanged();
            }
        }
        private Nullable<global::System.Double> _SYQMJ;
        partial void OnSYQMJChanging(Nullable<global::System.Double> value);
        partial void OnSYQMJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LXDH
        {
            get
            {
                return _LXDH;
            }
            set
            {
                OnLXDHChanging(value);
                ReportPropertyChanging("LXDH");
                _LXDH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LXDH");
                OnLXDHChanged();
            }
        }
        private global::System.String _LXDH;
        partial void OnLXDHChanging(global::System.String value);
        partial void OnLXDHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LXDHSJ
        {
            get
            {
                return _LXDHSJ;
            }
            set
            {
                OnLXDHSJChanging(value);
                ReportPropertyChanging("LXDHSJ");
                _LXDHSJ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LXDHSJ");
                OnLXDHSJChanged();
            }
        }
        private global::System.String _LXDHSJ;
        partial void OnLXDHSJChanging(global::System.String value);
        partial void OnLXDHSJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DZYJ
        {
            get
            {
                return _DZYJ;
            }
            set
            {
                OnDZYJChanging(value);
                ReportPropertyChanging("DZYJ");
                _DZYJ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DZYJ");
                OnDZYJChanged();
            }
        }
        private global::System.String _DZYJ;
        partial void OnDZYJChanging(global::System.String value);
        partial void OnDZYJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FRDB
        {
            get
            {
                return _FRDB;
            }
            set
            {
                OnFRDBChanging(value);
                ReportPropertyChanging("FRDB");
                _FRDB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FRDB");
                OnFRDBChanged();
            }
        }
        private global::System.String _FRDB;
        partial void OnFRDBChanging(global::System.String value);
        partial void OnFRDBChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FRZW
        {
            get
            {
                return _FRZW;
            }
            set
            {
                OnFRZWChanging(value);
                ReportPropertyChanging("FRZW");
                _FRZW = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FRZW");
                OnFRZWChanged();
            }
        }
        private global::System.String _FRZW;
        partial void OnFRZWChanging(global::System.String value);
        partial void OnFRZWChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FRLXDW
        {
            get
            {
                return _FRLXDW;
            }
            set
            {
                OnFRLXDWChanging(value);
                ReportPropertyChanging("FRLXDW");
                _FRLXDW = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FRLXDW");
                OnFRLXDWChanged();
            }
        }
        private global::System.String _FRLXDW;
        partial void OnFRLXDWChanging(global::System.String value);
        partial void OnFRLXDWChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FRSFZH
        {
            get
            {
                return _FRSFZH;
            }
            set
            {
                OnFRSFZHChanging(value);
                ReportPropertyChanging("FRSFZH");
                _FRSFZH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FRSFZH");
                OnFRSFZHChanged();
            }
        }
        private global::System.String _FRSFZH;
        partial void OnFRSFZHChanging(global::System.String value);
        partial void OnFRSFZHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FRTXDZ
        {
            get
            {
                return _FRTXDZ;
            }
            set
            {
                OnFRTXDZChanging(value);
                ReportPropertyChanging("FRTXDZ");
                _FRTXDZ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FRTXDZ");
                OnFRTXDZChanged();
            }
        }
        private global::System.String _FRTXDZ;
        partial void OnFRTXDZChanging(global::System.String value);
        partial void OnFRTXDZChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FRYB
        {
            get
            {
                return _FRYB;
            }
            set
            {
                OnFRYBChanging(value);
                ReportPropertyChanging("FRYB");
                _FRYB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FRYB");
                OnFRYBChanged();
            }
        }
        private global::System.String _FRYB;
        partial void OnFRYBChanging(global::System.String value);
        partial void OnFRYBChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LXR
        {
            get
            {
                return _LXR;
            }
            set
            {
                OnLXRChanging(value);
                ReportPropertyChanging("LXR");
                _LXR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LXR");
                OnLXRChanged();
            }
        }
        private global::System.String _LXR;
        partial void OnLXRChanging(global::System.String value);
        partial void OnLXRChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ZZRQ
        {
            get
            {
                return _ZZRQ;
            }
            set
            {
                OnZZRQChanging(value);
                ReportPropertyChanging("ZZRQ");
                _ZZRQ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZZRQ");
                OnZZRQChanged();
            }
        }
        private Nullable<global::System.DateTime> _ZZRQ;
        partial void OnZZRQChanging(Nullable<global::System.DateTime> value);
        partial void OnZZRQChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Models", "FK_UserInstance_Instance", "UserInstance")]
        public EntityCollection<UserInstance> UserInstance
        {
            internal get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserInstance>("Models.FK_UserInstance_Instance", "UserInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserInstance>("Models.FK_UserInstance_Instance", "UserInstance", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Models", Name="UserInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserInformation : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 UserInformation 对象。
        /// </summary>
        /// <param name="userID">UserID 属性的初始值。</param>
        public static UserInformation CreateUserInformation(global::System.Guid userID)
        {
            UserInformation userInformation = new UserInformation();
            userInformation.UserID = userID;
            return userInformation;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String trueName
        {
            get
            {
                return _trueName;
            }
            set
            {
                OntrueNameChanging(value);
                ReportPropertyChanging("trueName");
                _trueName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("trueName");
                OntrueNameChanged();
            }
        }
        private global::System.String _trueName;
        partial void OntrueNameChanging(global::System.String value);
        partial void OntrueNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telephone
        {
            get
            {
                return _telephone;
            }
            set
            {
                OntelephoneChanging(value);
                ReportPropertyChanging("telephone");
                _telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telephone");
                OntelephoneChanged();
            }
        }
        private global::System.String _telephone;
        partial void OntelephoneChanging(global::System.String value);
        partial void OntelephoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Guid _UserID;
        partial void OnUserIDChanging(global::System.Guid value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserType
        {
            get
            {
                return _UserType;
            }
            set
            {
                OnUserTypeChanging(value);
                ReportPropertyChanging("UserType");
                _UserType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserType");
                OnUserTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _UserType;
        partial void OnUserTypeChanging(Nullable<global::System.Int32> value);
        partial void OnUserTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Models", Name="UserInstance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserInstance : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 UserInstance 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="createUser">CreateUser 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        /// <param name="instanceID">InstanceID 属性的初始值。</param>
        /// <param name="qLRMC">QLRMC 属性的初始值。</param>
        /// <param name="fWZL">FWZL 属性的初始值。</param>
        public static UserInstance CreateUserInstance(global::System.String id, global::System.Guid createUser, global::System.DateTime createTime, global::System.Int32 instanceID, global::System.String qLRMC, global::System.String fWZL)
        {
            UserInstance userInstance = new UserInstance();
            userInstance.ID = id;
            userInstance.CreateUser = createUser;
            userInstance.CreateTime = createTime;
            userInstance.InstanceID = instanceID;
            userInstance.QLRMC = qLRMC;
            userInstance.FWZL = fWZL;
            return userInstance;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private global::System.Guid _CreateUser;
        partial void OnCreateUserChanging(global::System.Guid value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InstanceID
        {
            get
            {
                return _InstanceID;
            }
            set
            {
                OnInstanceIDChanging(value);
                ReportPropertyChanging("InstanceID");
                _InstanceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InstanceID");
                OnInstanceIDChanged();
            }
        }
        private global::System.Int32 _InstanceID;
        partial void OnInstanceIDChanging(global::System.Int32 value);
        partial void OnInstanceIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QLRMC
        {
            get
            {
                return _QLRMC;
            }
            set
            {
                OnQLRMCChanging(value);
                ReportPropertyChanging("QLRMC");
                _QLRMC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QLRMC");
                OnQLRMCChanged();
            }
        }
        private global::System.String _QLRMC;
        partial void OnQLRMCChanging(global::System.String value);
        partial void OnQLRMCChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FWZL
        {
            get
            {
                return _FWZL;
            }
            set
            {
                OnFWZLChanging(value);
                ReportPropertyChanging("FWZL");
                _FWZL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FWZL");
                OnFWZLChanged();
            }
        }
        private global::System.String _FWZL;
        partial void OnFWZLChanging(global::System.String value);
        partial void OnFWZLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RetreatReason
        {
            get
            {
                return _RetreatReason;
            }
            set
            {
                OnRetreatReasonChanging(value);
                ReportPropertyChanging("RetreatReason");
                _RetreatReason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RetreatReason");
                OnRetreatReasonChanged();
            }
        }
        private global::System.String _RetreatReason;
        partial void OnRetreatReasonChanging(global::System.String value);
        partial void OnRetreatReasonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CommitTime
        {
            get
            {
                return _CommitTime;
            }
            set
            {
                OnCommitTimeChanging(value);
                ReportPropertyChanging("CommitTime");
                _CommitTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommitTime");
                OnCommitTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CommitTime;
        partial void OnCommitTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCommitTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReturnTime
        {
            get
            {
                return _ReturnTime;
            }
            set
            {
                OnReturnTimeChanging(value);
                ReportPropertyChanging("ReturnTime");
                _ReturnTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnTime");
                OnReturnTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReturnTime;
        partial void OnReturnTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnReturnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AcceptedTime
        {
            get
            {
                return _AcceptedTime;
            }
            set
            {
                OnAcceptedTimeChanging(value);
                ReportPropertyChanging("AcceptedTime");
                _AcceptedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AcceptedTime");
                OnAcceptedTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _AcceptedTime;
        partial void OnAcceptedTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnAcceptedTimeChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Models", "FK_UserInstance_Instance", "Instance")]
        public Instance Instance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instance>("Models.FK_UserInstance_Instance", "Instance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instance>("Models.FK_UserInstance_Instance", "Instance").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Instance> InstanceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instance>("Models.FK_UserInstance_Instance", "Instance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Instance>("Models.FK_UserInstance_Instance", "Instance", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
